### ISSUE TITLE
Docker invocation

### ISSUE THREAD

**Issue by pwighton** [mnoergaard/petprep_hmc#11]
I had to alter the docker invocation slightly from what is in the readme to get it to work.

1)  I had to define the environment variable `SUBJECTS_DIR` to make FreeSurfer happy, 

2) I had to append `/usr/local/fsl/bin` to the `PATH` so that it could find `fslmaths`.  Note FSL is installed in `/usr/local/fsl` and not `/opt/fsl`.  `/usr/local/fsl/bin` needs to come *after* `/usr/local/bin` in the `PATH`, otherwise FSL's python (3.10) will be used to invoke `run.py`

3) I had to remove `python3 run.py` as it was interfering with argument parsing.

The command that worked looked like:

```
docker run -it --rm \
  -v /path/to/bids_input:/data/input \
  -v /path/to/bids_output:/data/output \
  -v /path/to/freesurfer_license:/opt/freesurfer/license.txt \
  -e SUBJECTS_DIR=/data/output \
  -e PATH=/opt/freesurfer/bin:/opt/freesurfer/fsfast/bin:/opt/freesurfer/tktools:/opt/fsl/bin:/opt/freesurfer/mni/bin:/opt/freesurfer/bin:/opt/fsl/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/fsl/bin \
  martinnoergaard/petprep_hmc:latest \
    --bids_dir /data/input \
    --output_dir /data/output
```

**Comment by mnoergaard** [comment]
Thanks for testing this, Paul! I have now updated the Docker file (and documentation) and the workflow structure, allowing for more flexibility around different subjects, sessions and runs. Would you mind testing it? Thanks!

**Comment by mnoergaard** [comment]
Should now be fixed and pushed to dockerhub. If any issues still persist, please re-open this issue. Thank you, Paul!
