### ISSUE TITLE
Add Makefile

### ISSUE THREAD

**Issue by bendhouseart** [mnoergaard/petprep_hmc#23]
Adding a Makefile provides us with a consistent way to execute developer commands

During testing and development it's helpful to have access to linting/formatting as well
as docker build and upload commands that properly tag and upload new releases of images.
- docker build
- docker push
- black **/*.py

Later these "local" commands can be used in CI so that local and automated testing steps 
are reproducible.

**Comment by mnoergaard** [comment]
Closed as completed via #24
